name: AlphaMeterQC
version: 1.0.0
schema: v1


models:

# ========= Облачные =========

yandex_cloud: &yandex_cloud
  provider: openai
  apiBase: https://ai.api.cloud.yandex.net/v1
  apiKey: ${{ secrets.AISTUDIO_API_KEY }}
  requestOptions:
    headers:
      OpenAI-Project: ${{ secrets.AISTUDIO_FOLDER_ID }}

  - name: Qwen3 235B
    <<: *yandex_cloud
    model: gpt://${{ secrets.AISTUDIO_FOLDER_ID }}/qwen3-235b-a22b-fp8

  - name: DeepSeek V4 Flash
    <<: *yandex_cloud
    model: gpt://${{ secrets.AISTUDIO__FOLDER_ID }}/deepseek-v4-flash/latest

  - name: Qwen3.6-35B
    <<: *yandex_cloud
    model: gpt://${{ secrets.AISTUDIO__FOLDER_ID }}/qwen3.6-35b-a3b

  - name: gpt-oss-20b
    <<: *yandex_cloud
    model: gpt://${{ secrets.AISTUDIO__FOLDER_ID }}/gpt-oss-20b/latest

  - name: Alice AI LLM Flash
    <<: *yandex_cloud
    model: gpt://${{ secrets.AISTUDIO__FOLDER_ID }}/aliceai-llm-flash/latest

# ========= Локальные =========

ollama: &ollama
  provider: ollama
  apiBase: http://localhost:11434

  - name: mistral:7b
    <<: *ollama
    model: mistral:7b
  
  - name: qwen2.5:7b
    <<: *ollama
    model: qwen2.5:7b
  
  - name: qwen3.5:4b
    <<: *ollama
    model: qwen3.5:4b

# Coder
  - name: deepseek-coder:6.7b
    <<: *ollama
    model: deepseek-coder:6.7b

  - name: qwen2.5-coder:7b
    <<: *ollama
    model: qwen2.5-coder:7b

  - name: qwen2.5-coder:3b
    <<: *ollama
    model: qwen2.5-coder:3b

  - name: qwen2.5-coder:1.5b
    <<: *ollama
    model: qwen2.5-coder:1.5b

  - name: nomic-embed
    <<: *ollama
    model: nomic-embed-text:latest
