name: alphameterqc
version: 1.0.0
schema: v1
models:
  - name: mistral:7b
    provider: ollama
    model: mistral:7b
    apiBase: http://localhost:11434
    roles:
      - chat
      - apply
    defaultCompletionOptions:
      maxTokens: 4096 #8192
    capabilities:
      - tool_use
      - image_input
  - name: qwen3.5:4b
    provider: ollama
    model: qwen3.5:4b
    apiBase: http://localhost:11434
    roles:
      - chat
      - apply
      - autocomplete
    defaultCompletionOptions:
      maxTokens: 4096 #8192
    capabilities:
      - tool_use
      - image_input
  - name: qwen2.5-coder:3b
    provider: ollama
    model: qwen2.5-coder:3b
    apiBase: http://localhost:11434
    roles:
      - edit
      - apply
      - autocomplete
    defaultCompletionOptions:
      maxTokens: 8192
      temperature: 0.5
      topP: 0.85
      stop:
        - \n\n
        - </s>
    capabilities:
      - tool_use
      - image_input
